version: '3'

services:
  sonarqube: 
    image: sonarqube:lts
    container_name: sonarqube_sonar
    # restart: unless-stopped
    logging:
      driver: "journald"
    ports:
      - "9000:9000"
      - "9092:9092"
    links:
      - db
    depends_on:
      - db
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - /developments/dockers/sonarqube/conf:/opt/sonarqube/conf
      - /developments/dockers/sonarqube/data:/opt/sonarqube/data
      - /developments/dockers/sonarqube/extensions:/opt/sonarqube/extensions
      - /developments/dockers/sonarqube/plugins:/opt/sonarqube/lib/bundled-plugins

  db:
    image: postgres:9.6
    # restart: unless-stopped
    logging:
      driver: "journald"
    ports:
      - "5432"
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    volumes:
      - /developments/dockers/sonarqube/db:/var/lib/postgresql/data

