
server:
  port: 6001

spring.application.name: Soul Land

info:
  group: io.boonlogc
  artifact: soul-land
  name: Soul Land Application
  version: 1.6.5

# Sample Configuration from SpringBoot => FF4J
security:
  user:
    name: ff4j
    password: ff4j

ff4j:
  webapi:
    authentication: false
    authorization: false

