
server:
  port: 8761

endpoints:
  shutdown:
    enabled: true

management:
  security:
    enabled: false

eureka:
  environment: production
  datacenter: boonlogic
#  client:
#    register-with-eureka: false           # standalone mode, disable peer awareness
#    fetch-registry: false                 # disable caching of registry information locally
#  server:
#    wait-time-in-ms-when-sync-empty: 5    # initial time to wait before server takes requests


  instance:
    prefer-ip-address: true

---
spring:
  profiles: registry1

server:
  port: 8761

eureka:
  instance:
    hostname: registry1
    instanceId: ${eureka.instance.hostname}-${server.port}
  client:
    service-url:
      defaultZone: http://registry2:8762/eureka/
---
spring:
  profiles: registry2

server:
  port: 8762

eureka:
  instance:
    hostname: registry2
    instanceId: ${eureka.instance.hostname}-${server.port}
  client:
    service-url:
      defaultZone: http://registry1:8761/eureka/

