
spring:
  profiles:
    active: default

server:
  port: 0
  undertow:
    accesslog:
      enabled: true
      dir: /home/boonheng/

eureka:
  instance:
    prefer-ip-address: true
    instanceId: ${spring.application.name}-${spring.cloud.client.ipAddress}:${server.port}-${INSTANCE_ID:${random.value}}

  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761,http://localhost:8762